### ISSUE TITLE
Add Eclipse Temurin builds

### ISSUE THREAD

**Issue by mateusz-bajorek** [ScoopInstaller/Java#307] opened 2021-09-24 12:51 UTC
AdoptOpenJDK is being migrated over to Eclipse foundation, with the homepage being https://adoptium.net

The available versions are 8, 11, 16 and 17: https://adoptium.net/archive.html

Also, the J9 JVM won't be used anymore in those builds, only Hotspot.

Unfortunately, looks like https://api.adoptium.net/ isn't fully functional yet...

**Comment by se35710** [comment] 2021-09-29 20:07
I'm doing rework of all the old AdoptOpenJDK manifests, changing the hotspot ones (except for RedHat upstream builds) to Temurin and OpenJ9 builds to IBM Semeru. That work is tracked by issue #100 but is still WIP.

Duplicate of #100

**Closed by se35710** 2021-09-29 20:07 UTC
