### ISSUE TITLE
oraclejre8@8u431: decompress error

### ISSUE THREAD

**Issue by wu0lss4j** [ScoopInstaller/Java#532] opened 2024-10-16 19:41 UTC
Updating 'oraclejre8' (8u421 -> 8u431)
Downloading new version
dl.tar.gz (10,9 KB) [=============================================================================================================================================================================================================] 100%
Checking hash of dl.tar.gz ... ok.
Uninstalling 'oraclejre8' (8u421)
Installing 'oraclejre8' (8u431) [64bit] from 'java' bucket
Loading dl.tar.gz from cache
Extracting dl.tar.gz ... ERROR Exit code was 2!
Failed to extract files from C:\Users\tcj4evr\scoop\apps\oraclejre8\8u431\dl.tar.gz.
Log file:
  ~\scoop\apps\oraclejre8\8u431\7zip.log

I believe the error has to do with the (10,9 KB) size of the dl.tar.gz ← Also I cannot find the 7zip.log

#### Scoop Configuration

```json
//# Your configuration here
```

**Comment by se35710** [comment] 2024-10-18 08:26
Duplicate of #530

**Closed as completed by se35710** 2024-10-18 08:26 UTC
