### ISSUE TITLE
ojdkbuild8-full@1.8.0.312-1.b07: decompress error

### ISSUE THREAD

**Issue by Werewolfnman** [ScoopInstaller/Java#342] opened 2021-11-29 20:26 UTC
PS C:\Users\acber> scoop install ojdkbuild8-full
Installing 'ojdkbuild8-full' (1.8.0.312-1.b07) [64bit]
java-1.8.0-openjdk-1.8.0.312-1.b07.ojdkbuild.windows.x86_64.msi (210.1 MB) [==================================] 100%
Checking hash of java-1.8.0-openjdk-1.8.0.312-1.b07.ojdkbuild.windows.x86_64.msi ... ok.
Extracting java-1.8.0-openjdk-1.8.0.312-1.b07.ojdkbuild.windows.x86_64.msi ... ERROR Exit code was 1603!
Failed to extract files from C:\Users\acber\scoop\apps\ojdkbuild8-full\1.8.0.312-1.b07\java-1.8.0-openjdk-1.8.0.312-1.b07.ojdkbuild.windows.x86_64.msi.
Log file:
  ~\scoop\apps\ojdkbuild8-full\1.8.0.312-1.b07\msi.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Java/issues/new?title=ojdkbuild8-full%401.8.0.312-1.b07%3a+decompress+error
PS C:\Users\acber> scoop install ojdkbuild8-full
WARN  Purging previous failed installation of ojdkbuild8-full.
Uninstalling 'ojdkbuild8-full' ().
'ojdkbuild8-full' was uninstalled.
Installing 'ojdkbuild8-full' (1.8.0.312-1.b07) [64bit]
Loading java-1.8.0-openjdk-1.8.0.312-1.b07.ojdkbuild.windows.x86_64.msi from cache
Checking hash of java-1.8.0-openjdk-1.8.0.312-1.b07.ojdkbuild.windows.x86_64.msi ... ok.
Extracting java-1.8.0-openjdk-1.8.0.312-1.b07.ojdkbuild.windows.x86_64.msi ... ERROR Exit code was 1603!
Failed to extract files from C:\Users\acber\scoop\apps\ojdkbuild8-full\1.8.0.312-1.b07\java-1.8.0-openjdk-1.8.0.312-1.b07.ojdkbuild.windows.x86_64.msi.
Log file:
  ~\scoop\apps\ojdkbuild8-full\1.8.0.312-1.b07\msi.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Java/issues/new?title=ojdkbuild8-full%401.8.0.312-1.b07%3a+decompress+error

**Comment by se35710** [comment] 2021-11-30 20:32
Duplicate of #72

**Closed by se35710** 2021-11-30 20:32 UTC
