### ISSUE TITLE
oraclejre8@8u431: decompress error

### ISSUE THREAD

**Issue by themagicalmammal** [ScoopInstaller/Java#538] opened 2024-11-25 11:21 UTC
#### Scoop Installation Error

```
oraclejre8: 8u421 -> 8u431
Updating one outdated app:
Updating 'oraclejre8' (8u421 -> 8u431)
Downloading new version
Loading dl.tar.gz from cache
Checking hash of dl.tar.gz ... ok.
Uninstalling 'oraclejre8' (8u421)
Installing 'oraclejre8' (8u431) [64bit] from 'java' bucket
Loading dl.tar.gz from cache
Extracting dl.tar.gz ... ERROR Exit code was 2!
Failed to extract files from C:\Users\DipanNanda\scoop\apps\oraclejre8\8u431\dl.tar.gz.
Log file:
  ~\scoop\apps\oraclejre8\8u431\7zip.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Java/issues/new?title=oraclejre8%408u431%3a+decompress+error
```

**Comment by themagicalmammal** [comment] 2024-11-25 11:23
Log is

```
7-Zip 24.08 (x64) : Copyright (c) 1999-2024 Igor Pavlov : 2024-08-11

Scanning the drive for archives:
1 file, 11175 bytes (11 KiB)

Extracting archive: C:\Users\DipanNanda\scoop\apps\oraclejre8\8u431\dl.tar.gz

Can't open as archive: 1
Files: 0
Size:       0
Compressed: 0
ERROR: C:\Users\DipanNanda\scoop\apps\oraclejre8\8u431\dl.tar.gz
C:\Users\DipanNanda\scoop\apps\oraclejre8\8u431\dl.tar.gz
Open ERROR: Cannot open the file as [gzip] archive


ERRORS:
Is not archive

7-Zip 24.08 (x64) : Copyright (c) 1999-2024 Igor Pavlov : 2024-08-11

Scanning the drive for archives:
1 file, 11175 bytes (11 KiB)

Extracting archive: C:\Users\DipanNanda\scoop\apps\oraclejre8\8u431\dl.tar.gz

Can't open as archive: 1
Files: 0
Size:       0
Compressed: 0
ERROR: C:\Users\DipanNanda\scoop\apps\oraclejre8\8u431\dl.tar.gz
C:\Users\DipanNanda\scoop\apps\oraclejre8\8u431\dl.tar.gz
Open ERROR: Cannot open the file as [gzip] archive


ERRORS:
Is not archive

7-Zip 24.08 (x64) : Copyright (c) 1999-2024 Igor Pavlov : 2024-08-11

Scanning the drive for archives:
1 file, 11175 bytes (11 KiB)

Extracting archive: C:\Users\DipanNanda\scoop\apps\oraclejre8\8u431\dl.tar.gz

Can't open as archive: 1
Files: 0
Size:       0
Compressed: 0
ERROR: C:\Users\DipanNanda\scoop\apps\oraclejre8\8u431\dl.tar.gz
C:\Users\DipanNanda\scoop\apps\oraclejre8\8u431\dl.tar.gz
Open ERROR: Cannot open the file as [gzip] archive


ERRORS:
Is not archive

7-Zip 24.08 (x64) : Copyright (c) 1999-2024 Igor Pavlov : 2024-08-11

Scanning the drive for archives:
1 file, 11175 bytes (11 KiB)

Extracting archive: C:\Users\DipanNanda\scoop\apps\oraclejre8\8u431\dl.tar.gz

Can't open as archive: 1
Files: 0
Size:       0
Compressed: 0
ERROR: C:\Users\DipanNanda\scoop\apps\oraclejre8\8u431\dl.tar.gz
C:\Users\DipanNanda\scoop\apps\oraclejre8\8u431\dl.tar.gz
Open ERROR: Cannot open the file as [gzip] archive


ERRORS:
Is not archive

7-Zip 24.08 (x64) : Copyright (c) 1999-2024 Igor Pavlov : 2024-08-11

Scanning the drive for archives:
1 file, 11175 bytes (11 KiB)

Extracting archive: C:\Users\DipanNanda\scoop\apps\oraclejre8\8u431\dl.tar.gz

Can't open as archive: 1
Files: 0
Size:       0
Compressed: 0
ERROR: C:\Users\DipanNanda\scoop\apps\oraclejre8\8u431\dl.tar.gz
C:\Users\DipanNanda\scoop\apps\oraclejre8\8u431\dl.tar.gz
Open ERROR: Cannot open the file as [gzip] archive


ERRORS:
Is not archive

7-Zip 24.08 (x64) : Copyright (c) 1999-2024 Igor Pavlov : 2024-08-11

Scanning the drive for archives:
1 file, 11175 bytes (11 KiB)

Extracting archive: C:\Users\DipanNanda\scoop\apps\oraclejre8\8u431\dl.tar.gz

Can't open as archive: 1
Files: 0
Size:       0
Compressed: 0
ERROR: C:\Users\DipanNanda\scoop\apps\oraclejre8\8u431\dl.tar.gz
C:\Users\DipanNanda\scoop\apps\oraclejre8\8u431\dl.tar.gz
Open ERROR: Cannot open the file as [gzip] archive


ERRORS:
Is not archive

7-Zip 24.08 (x64) : Copyright (c) 1999-2024 Igor Pavlov : 2024-08-11

Scanning the drive for archives:
1 file, 11175 bytes (11 KiB)

Extracting archive: C:\Users\DipanNanda\scoop\apps\oraclejre8\8u431\dl.tar.gz

Can't open as archive: 1
Files: 0
Size:       0
Compressed: 0
ERROR: C:\Users\DipanNanda\scoop\apps\oraclejre8\8u431\dl.tar.gz
C:\Users\DipanNanda\scoop\apps\oraclejre8\8u431\dl.tar.gz
Open ERROR: Cannot open the file as [gzip] archive


ERRORS:
Is not archive

7-Zip 24.08 (x64) : Copyright (c) 1999-2024 Igor Pavlov : 2024-08-11

Scanning the drive for archives:
1 file, 11175 bytes (11 KiB)

Extracting archive: C:\Users\DipanNanda\scoop\apps\oraclejre8\8u431\dl.tar.gz

Can't open as archive: 1
Files: 0
Size:       0
Compressed: 0
ERROR: C:\Users\DipanNanda\scoop\apps\oraclejre8\8u431\dl.tar.gz
C:\Users\DipanNanda\scoop\apps\oraclejre8\8u431\dl.tar.gz
Open ERROR: Cannot open the file as [gzip] archive


ERRORS:
Is not archive

7-Zip 24.08 (x64) : Copyright (c) 1999-2024 Igor Pavlov : 2024-08-11

Scanning the drive for archives:
1 file, 11175 bytes (11 KiB)

Extracting archive: C:\Users\DipanNanda\scoop\apps\oraclejre8\8u431\dl.tar.gz

Can't open as archive: 1
Files: 0
Size:       0
Compressed: 0
ERROR: C:\Users\DipanNanda\scoop\apps\oraclejre8\8u431\dl.tar.gz
C:\Users\DipanNanda\scoop\apps\oraclejre8\8u431\dl.tar.gz
Open ERROR: Cannot open the file as [gzip] archive


ERRORS:
Is not archive

7-Zip 24.08 (x64) : Copyright (c) 1999-2024 Igor Pavlov : 2024-08-11

Scanning the drive for archives:
1 file, 11175 bytes (11 KiB)

Extracting archive: C:\Users\DipanNanda\scoop\apps\oraclejre8\8u431\dl.tar.gz

Can't open as archive: 1
Files: 0
Size:       0
Compressed: 0
ERROR: C:\Users\DipanNanda\scoop\apps\oraclejre8\8u431\dl.tar.gz
C:\Users\DipanNanda\scoop\apps\oraclejre8\8u431\dl.tar.gz
Open ERROR: Cannot open the file as [gzip] archive


ERRORS:
Is not archive
```

**Comment by themagicalmammal** [comment] 2024-11-25 11:25
#537

**Comment by themagicalmammal** [comment] 2024-11-25 11:26
#535

**Comment by themagicalmammal** [comment] 2024-11-25 11:26
#530

**Comment by se35710** [comment] 2024-11-25 12:04
Duplicate of #530

**Closed by se35710** 2024-11-25 12:04 UTC
