### ISSUE TITLE
oraclejre8@8u431: decompress error

### ISSUE THREAD

**Issue by nickmuoh** [ScoopInstaller/Java#537] opened 2024-11-18 17:20 UTC
I get the following error when running `sudo scoop update -g oraclejre8`

```
ERROR 'oraclejre8' isn't installed correctly.
oraclejre8: 8u421 -> 8u431 (global)
Updating one outdated app:
Updating 'oraclejre8' (8u421 -> 8u431)
Downloading new version
Loading dl.tar.gz from cache
Checking hash of dl.tar.gz ... ok.
Uninstalling 'oraclejre8' (8u421)
Installing 'oraclejre8' (8u431) [64bit] from 'java' bucket
Loading dl.tar.gz from cache
Extracting dl.tar.gz ... ERROR Exit code was 2!
Failed to extract files from C:\ProgramData\Scoop\apps\oraclejre8\8u431\dl.tar.gz.
Log file:
  C:\ProgramData\Scoop\apps\oraclejre8\8u431\7zip.log
```

Here is the log from 7zip:

```
7-Zip 24.08 (x64) : Copyright (c) 1999-2024 Igor Pavlov : 2024-08-11

Scanning the drive for archives:
1 file, 11175 bytes (11 KiB)

Extracting archive: C:\ProgramData\Scoop\apps\oraclejre8\8u431\dl.tar.gz

Can't open as archive: 1
Files: 0
Size:       0
Compressed: 0
ERROR: C:\ProgramData\Scoop\apps\oraclejre8\8u431\dl.tar.gz
C:\ProgramData\Scoop\apps\oraclejre8\8u431\dl.tar.gz
Open ERROR: Cannot open the file as [gzip] archive


ERRORS:
Is not archive
```

**Comment by themagicalmammal** [comment] 2024-11-25 11:27
#538 Might be related

**Comment by se35710** [comment] 2024-11-25 12:03
Duplicate of #530

**Closed by se35710** 2024-11-25 12:03 UTC
