### ISSUE TITLE
ojdkbuild8-full@1.8.0.282-1.b08: decompress error

### ISSUE THREAD

**Issue by themrhead** [ScoopInstaller/Java#285] opened 2021-05-07 19:23 UTC
❯ scoop install ojdkbuild8-full
Installing 'ojdkbuild8-full' (1.8.0.282-1.b08) [64bit]
Loading java-1.8.0-openjdk-1.8.0.282-1.b08.ojdkbuild.windows.x86_64.msi from cache
Checking hash of java-1.8.0-openjdk-1.8.0.282-1.b08.ojdkbuild.windows.x86_64.msi ... ok.
Extracting java-1.8.0-openjdk-1.8.0.282-1.b08.ojdkbuild.windows.x86_64.msi ... ERROR Exit code was 1603!
Failed to extract files from D:\tools\apps\ojdkbuild8-full\1.8.0.282-1.b08\java-1.8.0-openjdk-1.8.0.282-1.b08.ojdkbuild.windows.x86_64.msi.
Log file:
  D:\tools\apps\ojdkbuild8-full\1.8.0.282-1.b08\msi.log

**Comment by se35710** [comment] 2021-05-27 06:34
Duplicate of #72

**Closed by se35710** 2021-05-27 06:34 UTC
