### ISSUE TITLE
Update zulu

### ISSUE THREAD

**Issue by edgardmessias** [ScoopInstaller/Java#69] opened 2019-07-17 20:59 UTC
New home page: https://www.azul.com/downloads/zulu-community/

Available files: https://cdn.azul.com/zulu/bin/?C=N;O=A
Checksum: https://www.azul.com/wp-admin/admin-ajax.php?action=search_bundles

**Comment by se35710** [comment] 2019-11-09 08:31
We should harmonize all Zulu manifest's `checkver` and `autoupdate`s, PR #97 is using https://api.azul.com/, some of the other Zulu manifest are using https://zulu.api.azul.com/.

- For https://www.azul.com/wp-admin/admin-ajax.php?action=search_bundles we don't have proper jsonpath support.
- For https://zulu.api.azul.com/ there is heavy rate limiting active, so `auto-pr` might fail.
- For https://api.azul.com/ I am having issues with i686/x86_64.

**Comment by h404bi** [comment] 2019-11-09 10:39
> For https://api.azul.com/ I am having issues with i686/x86_64.

Yes, me too. If I query the latest bundle with the parameter 'hw_bitness=32' it will always return 'not found'.

64bit (OK):
https://api.azul.com/zulu/download/community/v1.0/bundles/latest/?os=windows&arch=x86&hw_bitness=64&bundle_type=jdk&ext=zip

32bit (Not Found):
https://api.azul.com/zulu/download/community/v1.0/bundles/latest/?os=windows&arch=x86&hw_bitness=32&bundle_type=jdk&ext=zip

But in fact, the 32bit bundle is available. For example:

https://api.azul.com/zulu/download/community/v1.0/bundles/1147/

The problem is the 'hw_bitness' value of the 32bit bundle is marked as '64'. I have reported this API issue to Azul Support. Waiting for response.

**Closed** 2019-11-11 20:46 UTC
Labels: help wanted

**Comment by h404bi** [comment] 2019-11-25 04:19
> > For https://api.azul.com/ I am having issues with i686/x86_64.
> 
> Yes, me too. If I query the latest bundle with the parameter 'hw_bitness=32' it will always return 'not found'.
> 
> 64bit (OK):
> https://api.azul.com/zulu/download/community/v1.0/bundles/latest/?os=windows&arch=x86&hw_bitness=64&bundle_type=jdk&ext=zip
> 
> 32bit (Not Found):
> https://api.azul.com/zulu/download/community/v1.0/bundles/latest/?os=windows&arch=x86&hw_bitness=32&bundle_type=jdk&ext=zip
> 
> But in fact, the 32bit bundle is available. For example:
> 
> https://api.azul.com/zulu/download/community/v1.0/bundles/1147/
> 
> The problem is the 'hw_bitness' value of the 32bit bundle is marked as '64'. I have reported this API issue to Azul Support. Waiting for response.

I just received the support e-mail saying this issue was fixed by Azul. Now you can query 32-bit bundles from https://api.azul.com/zulu/download/community/v1.0/bundles/latest/?os=windows&arch=x86&hw_bitness=32&bundle_type=jdk&ext=zip

Using official download API should be better than https://www.azul.com/wp-admin/admin-ajax.php?action=search_bundles
