### ISSUE TITLE
Update GraalVM to 21.0

### ISSUE THREAD

**Issue by qiyuey** [ScoopInstaller/Java#250] opened 2021-02-14 05:15 UTC
3KU

**Comment by se35710** [comment] 2021-02-26 08:45
Duplicate of #246

**Comment by pratikpc** [comment] 2021-04-01 08:10
@qiyuey I [added a PR](https://github.com/ScoopInstaller/Java/pull/255) to update GraalVM to 21 and also update the checkver URLs to the new GitHub links
Could you share your views?

**Closed** 2021-04-01 11:20 UTC
