### ISSUE TITLE
ojdkbuild8-full@1.8.0.292-1.b10: decompress error

### ISSUE THREAD

**Issue by Clinton4398** [ScoopInstaller/Java#297] opened 2021-07-22 00:48 UTC
https://github.com/ScoopInstaller/Java/issues/new?title=ojdkbuild8-full%401.8.0.292-1.b10%3a+decompress+error

**Comment by se35710** [comment] 2021-08-25 06:52
Duplicate of #72

**Closed by se35710** 2021-08-25 06:52 UTC
