### ISSUE TITLE
ojdkbuild8-full@1.8.0.275-1.b01: decompress error

### ISSUE THREAD

**Issue by MioBlanco** [ScoopInstaller/Java#229] opened 2020-11-16 15:03 UTC
```
C:\Windows\System32>scoop install ojdkbuild8-full
Installing 'ojdkbuild8-full' (1.8.0.275-1.b01) [64bit]
Loading java-1.8.0-openjdk-1.8.0.275-1.b01.ojdkbuild.windows.x86_64.msi from cache
Checking hash of java-1.8.0-openjdk-1.8.0.275-1.b01.ojdkbuild.windows.x86_64.msi ... ok.
Extracting java-1.8.0-openjdk-1.8.0.275-1.b01.ojdkbuild.windows.x86_64.msi ... ERROR Exit code was 1603!
Failed to extract files from C:\Users\nwe\scoop\apps\ojdkbuild8-full\1.8.0.275-1.b01\java-1.8.0-openjdk-1.8.0.275-1.b01.ojdkbuild.windows.x86_64.msi.
Log file:
  ~\scoop\apps\ojdkbuild8-full\1.8.0.275-1.b01\msi.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Java/issues/new?title=ojdkbuild8-full%401.8.0.275-1.b01%3a+decompress+error
```
Log File:
[msi.log](https://github.com/ScoopInstaller/Java/files/5547114/msi.log)

**Comment by se35710** [comment] 2020-11-19 14:36
Duplicate of #72

**Closed by se35710** 2020-11-19 14:36 UTC
